2025-03-08 12:45:19,410 INFO    Thread-2 (_run_job):10980 [wandb_init.py:setup_run_log_directory():647] Logging user logs to K:\DA6401\da6401_assignment1\wandb\run-20250308_124519-z8h91can\logs\debug.log
2025-03-08 12:45:19,410 INFO    Thread-2 (_run_job):10980 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to K:\DA6401\da6401_assignment1\wandb\run-20250308_124519-z8h91can\logs\debug-internal.log
2025-03-08 12:45:19,411 INFO    Thread-2 (_run_job):10980 [wandb_init.py:init():761] calling init triggers
2025-03-08 12:45:19,411 INFO    Thread-2 (_run_job):10980 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 16, 'dataset': 'fashion_mnist', 'epochs': 10, 'hidden_size': 64, 'learning_rate': 0.0001, 'loss': 'mean_squared_error', 'num_layers': 4, 'optimizer': 'momentum', 'weight_decay': 0.5, 'weight_init': 'Xavier'}
config: {'wandb_project': 'da6401_a1', 'wandb_entity': 'da24m002-indian-institute-of-technology-madras', 'dataset': 'fashion_mnist', 'epochs': 10, 'batch_size': 16, 'loss': 'mean_squared_error', 'optimizer': 'momentum', 'learning_rate': 0.0001, 'momentum': 0.9, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.999, 'epsilon': 1e-08, 'weight_decay': 0.5, 'weight_init': 'Xavier', 'num_layers': 4, 'hidden_size': 64, 'activation': 'tanh', 'sweep': True, '_wandb': {}}
2025-03-08 12:45:19,411 INFO    Thread-2 (_run_job):10980 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-08 12:45:20,006 INFO    Thread-2 (_run_job):10980 [wandb_run.py:_finish():2112] finishing run da24m002-indian-institute-of-technology-madras/da6401_a1/z8h91can
2025-03-08 12:45:20,007 INFO    Thread-2 (_run_job):10980 [wandb_run.py:_atexit_cleanup():2342] got exitcode: 1
2025-03-08 12:45:20,007 INFO    Thread-2 (_run_job):10980 [wandb_run.py:_restore():2324] restore
2025-03-08 12:45:20,008 INFO    Thread-2 (_run_job):10980 [wandb_run.py:_restore():2330] restore done
2025-03-08 12:45:22,636 INFO    MsgRouterThr:10980 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-08 12:45:22,637 INFO    Thread-2 (_run_job):10980 [wandb_run.py:_footer_history_summary_info():3958] rendering history
2025-03-08 12:45:22,638 INFO    Thread-2 (_run_job):10980 [wandb_run.py:_footer_history_summary_info():3990] rendering summary
2025-03-08 12:45:22,638 INFO    Thread-2 (_run_job):10980 [wandb_run.py:_footer_sync_info():3919] logging synced files
2025-03-08 12:45:22,666 ERROR   MainThread:10980 [pyagent.py:_run_jobs_from_queue():234] Run z8h91can errored:
Traceback (most recent call last):
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'momentum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "K:\DA6401\da6401_assignment1\train.py", line 294, in sweep_train
    train_model(args)
  File "K:\DA6401\da6401_assignment1\train.py", line 168, in train_model
    optimizer_params['momentum'] = config.momentum
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\wandb_config.py", line 167, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'momentum'

2025-03-08 12:45:24,077 INFO    Thread-5 (_run_job):10980 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-08 12:45:24,078 INFO    Thread-5 (_run_job):10980 [wandb_setup.py:_flush():67] Configure stats pid to 10980
2025-03-08 12:45:24,078 INFO    Thread-5 (_run_job):10980 [wandb_setup.py:_flush():67] Loading settings from C:\Users\ANJALI VERMA\.config\wandb\settings
2025-03-08 12:45:24,078 INFO    Thread-5 (_run_job):10980 [wandb_setup.py:_flush():67] Loading settings from K:\DA6401\da6401_assignment1\wandb\settings
2025-03-08 12:45:24,078 INFO    Thread-5 (_run_job):10980 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-08 12:45:24,079 INFO    Thread-5 (_run_job):10980 [wandb_init.py:setup_run_log_directory():647] Logging user logs to K:\DA6401\da6401_assignment1\wandb\run-20250308_124524-ztb682lb\logs\debug.log
2025-03-08 12:45:24,080 INFO    Thread-5 (_run_job):10980 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to K:\DA6401\da6401_assignment1\wandb\run-20250308_124524-ztb682lb\logs\debug-internal.log
2025-03-08 12:45:24,080 INFO    Thread-5 (_run_job):10980 [wandb_init.py:init():761] calling init triggers
2025-03-08 12:45:24,080 INFO    Thread-5 (_run_job):10980 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 32, 'dataset': 'fashion_mnist', 'epochs': 10, 'hidden_size': 64, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 3, 'optimizer': 'nag', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-08 12:45:24,080 INFO    Thread-5 (_run_job):10980 [wandb_init.py:init():784] starting backend
2025-03-08 12:45:24,080 INFO    Thread-5 (_run_job):10980 [wandb_init.py:init():788] sending inform_init request
2025-03-08 12:45:24,083 INFO    Thread-5 (_run_job):10980 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-08 12:45:24,085 INFO    Thread-5 (_run_job):10980 [wandb_init.py:init():803] backend started and connected
2025-03-08 12:45:24,086 INFO    Thread-5 (_run_job):10980 [wandb_run.py:_config_callback():1261] config_cb None None {'activation': 'tanh', 'batch_size': 32, 'dataset': 'fashion_mnist', 'epochs': 10, 'hidden_size': 64, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 3, 'optimizer': 'nag', 'weight_decay': 0, 'weight_init': 'random'}
2025-03-08 12:45:24,088 INFO    Thread-5 (_run_job):10980 [wandb_init.py:init():896] updated telemetry
2025-03-08 12:45:24,089 INFO    Thread-5 (_run_job):10980 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-08 12:45:24,620 INFO    Thread-5 (_run_job):10980 [wandb_init.py:init():995] starting run threads in backend
2025-03-08 12:45:24,846 INFO    Thread-5 (_run_job):10980 [wandb_run.py:_console_start():2377] atexit reg
2025-03-08 12:45:24,846 INFO    Thread-5 (_run_job):10980 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-08 12:45:24,847 INFO    Thread-5 (_run_job):10980 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-08 12:45:24,847 INFO    Thread-5 (_run_job):10980 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-08 12:45:24,848 INFO    Thread-5 (_run_job):10980 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-08 12:45:24,860 INFO    Thread-5 (_run_job):10980 [wandb_init.py:setup_run_log_directory():647] Logging user logs to K:\DA6401\da6401_assignment1\wandb\run-20250308_124524-ztb682lb\logs\debug.log
2025-03-08 12:45:24,861 INFO    Thread-5 (_run_job):10980 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to K:\DA6401\da6401_assignment1\wandb\run-20250308_124524-ztb682lb\logs\debug-internal.log
2025-03-08 12:45:24,861 INFO    Thread-5 (_run_job):10980 [wandb_init.py:init():761] calling init triggers
2025-03-08 12:45:24,861 INFO    Thread-5 (_run_job):10980 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 32, 'dataset': 'fashion_mnist', 'epochs': 10, 'hidden_size': 64, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 3, 'optimizer': 'nag', 'weight_decay': 0, 'weight_init': 'random'}
config: {'wandb_project': 'da6401_a1', 'wandb_entity': 'da24m002-indian-institute-of-technology-madras', 'dataset': 'fashion_mnist', 'epochs': 10, 'batch_size': 32, 'loss': 'cross_entropy', 'optimizer': 'nag', 'learning_rate': 0.0001, 'momentum': 0.9, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.999, 'epsilon': 1e-08, 'weight_decay': 0, 'weight_init': 'random', 'num_layers': 3, 'hidden_size': 64, 'activation': 'tanh', 'sweep': True, '_wandb': {}}
2025-03-08 12:45:24,861 INFO    Thread-5 (_run_job):10980 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-08 12:45:25,470 INFO    Thread-5 (_run_job):10980 [wandb_run.py:_finish():2112] finishing run da24m002-indian-institute-of-technology-madras/da6401_a1/ztb682lb
2025-03-08 12:45:25,471 INFO    Thread-5 (_run_job):10980 [wandb_run.py:_atexit_cleanup():2342] got exitcode: 1
2025-03-08 12:45:25,471 INFO    Thread-5 (_run_job):10980 [wandb_run.py:_restore():2324] restore
2025-03-08 12:45:25,471 INFO    Thread-5 (_run_job):10980 [wandb_run.py:_restore():2330] restore done
2025-03-08 12:45:27,777 INFO    MsgRouterThr:10980 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-08 12:45:27,778 INFO    Thread-5 (_run_job):10980 [wandb_run.py:_footer_history_summary_info():3958] rendering history
2025-03-08 12:45:27,778 INFO    Thread-5 (_run_job):10980 [wandb_run.py:_footer_history_summary_info():3990] rendering summary
2025-03-08 12:45:27,778 INFO    Thread-5 (_run_job):10980 [wandb_run.py:_footer_sync_info():3919] logging synced files
2025-03-08 12:45:27,793 ERROR   MainThread:10980 [pyagent.py:_run_jobs_from_queue():234] Run ztb682lb errored:
Traceback (most recent call last):
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'momentum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "K:\DA6401\da6401_assignment1\train.py", line 294, in sweep_train
    train_model(args)
  File "K:\DA6401\da6401_assignment1\train.py", line 168, in train_model
    optimizer_params['momentum'] = config.momentum
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\wandb_config.py", line 167, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'momentum'

2025-03-08 12:45:29,705 INFO    Thread-8 (_run_job):10980 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-08 12:45:29,706 INFO    Thread-8 (_run_job):10980 [wandb_setup.py:_flush():67] Configure stats pid to 10980
2025-03-08 12:45:29,706 INFO    Thread-8 (_run_job):10980 [wandb_setup.py:_flush():67] Loading settings from C:\Users\ANJALI VERMA\.config\wandb\settings
2025-03-08 12:45:29,707 INFO    Thread-8 (_run_job):10980 [wandb_setup.py:_flush():67] Loading settings from K:\DA6401\da6401_assignment1\wandb\settings
2025-03-08 12:45:29,707 INFO    Thread-8 (_run_job):10980 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-08 12:45:29,707 INFO    Thread-8 (_run_job):10980 [wandb_init.py:setup_run_log_directory():647] Logging user logs to K:\DA6401\da6401_assignment1\wandb\run-20250308_124529-b9remrom\logs\debug.log
2025-03-08 12:45:29,708 INFO    Thread-8 (_run_job):10980 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to K:\DA6401\da6401_assignment1\wandb\run-20250308_124529-b9remrom\logs\debug-internal.log
2025-03-08 12:45:29,709 INFO    Thread-8 (_run_job):10980 [wandb_init.py:init():761] calling init triggers
2025-03-08 12:45:29,709 INFO    Thread-8 (_run_job):10980 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'ReLU', 'batch_size': 32, 'dataset': 'fashion_mnist', 'epochs': 10, 'hidden_size': 128, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 3, 'optimizer': 'nag', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-08 12:45:29,709 INFO    Thread-8 (_run_job):10980 [wandb_init.py:init():784] starting backend
2025-03-08 12:45:29,709 INFO    Thread-8 (_run_job):10980 [wandb_init.py:init():788] sending inform_init request
2025-03-08 12:45:29,713 INFO    Thread-8 (_run_job):10980 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-08 12:45:29,716 INFO    Thread-8 (_run_job):10980 [wandb_init.py:init():803] backend started and connected
2025-03-08 12:45:29,718 INFO    Thread-8 (_run_job):10980 [wandb_run.py:_config_callback():1261] config_cb None None {'activation': 'ReLU', 'batch_size': 32, 'dataset': 'fashion_mnist', 'epochs': 10, 'hidden_size': 128, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 3, 'optimizer': 'nag', 'weight_decay': 0, 'weight_init': 'random'}
2025-03-08 12:45:29,721 INFO    Thread-8 (_run_job):10980 [wandb_init.py:init():896] updated telemetry
2025-03-08 12:45:29,723 INFO    Thread-8 (_run_job):10980 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-08 12:45:30,189 INFO    Thread-8 (_run_job):10980 [wandb_init.py:init():995] starting run threads in backend
2025-03-08 12:45:30,357 INFO    Thread-8 (_run_job):10980 [wandb_run.py:_console_start():2377] atexit reg
2025-03-08 12:45:30,357 INFO    Thread-8 (_run_job):10980 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-08 12:45:30,357 INFO    Thread-8 (_run_job):10980 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-08 12:45:30,357 INFO    Thread-8 (_run_job):10980 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-08 12:45:30,358 INFO    Thread-8 (_run_job):10980 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-08 12:45:30,370 INFO    Thread-8 (_run_job):10980 [wandb_init.py:setup_run_log_directory():647] Logging user logs to K:\DA6401\da6401_assignment1\wandb\run-20250308_124530-b9remrom\logs\debug.log
2025-03-08 12:45:30,371 INFO    Thread-8 (_run_job):10980 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to K:\DA6401\da6401_assignment1\wandb\run-20250308_124530-b9remrom\logs\debug-internal.log
2025-03-08 12:45:30,371 INFO    Thread-8 (_run_job):10980 [wandb_init.py:init():761] calling init triggers
2025-03-08 12:45:30,371 INFO    Thread-8 (_run_job):10980 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'ReLU', 'batch_size': 32, 'dataset': 'fashion_mnist', 'epochs': 10, 'hidden_size': 128, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 3, 'optimizer': 'nag', 'weight_decay': 0, 'weight_init': 'random'}
config: {'wandb_project': 'da6401_a1', 'wandb_entity': 'da24m002-indian-institute-of-technology-madras', 'dataset': 'fashion_mnist', 'epochs': 10, 'batch_size': 32, 'loss': 'cross_entropy', 'optimizer': 'nag', 'learning_rate': 0.0001, 'momentum': 0.9, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.999, 'epsilon': 1e-08, 'weight_decay': 0, 'weight_init': 'random', 'num_layers': 3, 'hidden_size': 128, 'activation': 'ReLU', 'sweep': True, '_wandb': {}}
2025-03-08 12:45:30,371 INFO    Thread-8 (_run_job):10980 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-08 12:45:30,938 INFO    Thread-8 (_run_job):10980 [wandb_run.py:_finish():2112] finishing run da24m002-indian-institute-of-technology-madras/da6401_a1/b9remrom
2025-03-08 12:45:30,939 INFO    Thread-8 (_run_job):10980 [wandb_run.py:_atexit_cleanup():2342] got exitcode: 1
2025-03-08 12:45:30,940 INFO    Thread-8 (_run_job):10980 [wandb_run.py:_restore():2324] restore
2025-03-08 12:45:30,941 INFO    Thread-8 (_run_job):10980 [wandb_run.py:_restore():2330] restore done
2025-03-08 12:45:33,459 INFO    MsgRouterThr:10980 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-08 12:45:33,461 INFO    Thread-8 (_run_job):10980 [wandb_run.py:_footer_history_summary_info():3958] rendering history
2025-03-08 12:45:33,461 INFO    Thread-8 (_run_job):10980 [wandb_run.py:_footer_history_summary_info():3990] rendering summary
2025-03-08 12:45:33,462 INFO    Thread-8 (_run_job):10980 [wandb_run.py:_footer_sync_info():3919] logging synced files
2025-03-08 12:45:33,482 ERROR   MainThread:10980 [pyagent.py:_run_jobs_from_queue():234] Run b9remrom errored:
Traceback (most recent call last):
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'momentum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "K:\DA6401\da6401_assignment1\train.py", line 294, in sweep_train
    train_model(args)
  File "K:\DA6401\da6401_assignment1\train.py", line 168, in train_model
    optimizer_params['momentum'] = config.momentum
  File "C:\Users\ANJALI VERMA\anaconda3\envs\dl\lib\site-packages\wandb\sdk\wandb_config.py", line 167, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'momentum'

2025-03-08 12:45:33,547 ERROR   MainThread:10980 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
